# Copyright (C) 2024-2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

# Default values for gmc.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

proxy:
  httpProxy: ""
  httpsProxy: ""
  noProxy: ""

tokens:
  hugToken: ""

alternateTagging: false
namespace: chatqa

# Common tag & repository for all images. Override if needed for specific images.
common_tag: &tag "latest"
common_registry: &repo "docker.io/opea"

llm_model: &cpu_model "casperhansen/llama-3-8b-instruct-awq"
llm_model_gaudi: &hpu_model "mistralai/Mixtral-8x7B-Instruct-v0.1"

embedding_model_name: &embedding_model_name "BAAI/bge-base-en-v1.5"
# embedding_model_name: &embedding_model_name "BAAI/bge-large-en-v1.5"

# imagePullSecrets:
#   - name: regcred
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}
podLabels:
  control-plane: gmc-controller

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 3000
  fsGroup: 2000
  seccompProfile:
    type: RuntimeDefault

vllmSecurityContext:
  fsGroup: 2000
  runAsGroup: 3000
  runAsNonRoot: true
  runAsUser: 1000

securityContext:
  capabilities:
    drop:
      - ALL
  runAsNonRoot: true
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true

resources:
  limits:
    memory: 128Mi
  requests:
    cpu: 500m
    memory: 64Mi

livenessProbe:
  httpGet:
    path: /healthz
    port: gmc
  initialDelaySeconds: 30
  periodSeconds: 20
readinessProbe:
  httpGet:
    path: /readyz
    port: gmc
  initialDelaySeconds: 5
  periodSeconds: 10

# Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

nodeSelector: {}

tolerations: []

affinity: {}

service:
  type: ClusterIP

pvc:
  modelLlm:
    name: model-volume-llm
    accessMode: ReadWriteOnce
    storage: 100Gi
  modelEmbedding:
    name: model-volume-embedding
    accessMode: ReadWriteOnce
    storage: 20Gi
  modelReranker:
    name: model-volume-reranker
    accessMode: ReadWriteOnce
    storage: 10Gi
  vectorStore:
    name: vector-store-data
    accessMode: ReadWriteOnce
    storage: 20Gi

images:
  gmcManager:
    image: "erag-gmcmanager"
    repository: *repo
    tag: *tag
    pullPolicy: Always
  gmcRouter:
    image: "erag-gmcrouter"
    repository: *repo
    tag: *tag
    pullPolicy: Always
  dataprep-usvc:
    image: "erag-dataprep"
    repository: *repo
    tag: *tag
    pullPolicy: Always
  embedding-usvc:
    image: "erag-embedding"
    repository: *repo
    tag: *tag
    pullPolicy: Always
    envs:
      EMBEDDING_MODEL_NAME: *embedding_model_name
  reranking-usvc:
    image: "erag-reranking"
    repository: *repo
    tag: *tag
    pullPolicy: Always
  teirerank:
    image: "erag-teirerank"
    repository: *repo
    tag: *tag
    envfile: "src/comps/reranks/impl/model_server/tei/docker/.env.cpu"
  tei:
    envs:
      MODEL_ID: *embedding_model_name
  teirerank_gaudi:
    image: "erag-teirerank_gaudi"
    repository: *repo
    tag: *tag
    envfile: "src/comps/reranks/impl/model_server/tei/docker/.env.hpu"
  prompt-template-usvc:
    image: "erag-prompt_template"
    repository: *repo
    tag: *tag
    pullPolicy: Always
  torchserve_embedding:
    image: "erag-torchserve_embedding"
    repository: *repo
    tag: *tag
    pullPolicy: Always
    envfile: "src/comps/embeddings/impl/model-server/torchserve/docker/.env"
    envs:
      TORCHSERVE_MODEL_NAME: *embedding_model_name
  torchserve_reranking:
    image: "erag-torchserve_reranking"
    repository: *repo
    tag: *tag
    pullPolicy: Always
    envfile: "src/comps/reranks/impl/model_server/torchserve/docker/.env"
  retriever-usvc:
    image: "erag-retriever"
    repository: *repo
    tag: *tag
    pullPolicy: Always
    envfile: "src/comps/retrievers/impl/microservice/.env"
  ingestion-usvc:
    image: "erag-ingestion"
    repository: *repo
    tag: *tag
    pullPolicy: Always
    envfile: "src/comps/ingestion/impl/microservice/.env"
  llm-usvc:
    image: "erag-llm"
    repository: *repo
    tag: *tag
    pullPolicy: Always
    envfile: "src/comps/llms/impl/microservice/.env"
  in-guard-usvc:
    image: "erag-in-guard"
    repository: *repo
    tag: *tag
    pullPolicy: Always
  out-guard-usvc:
    image: "erag-out-guard"
    repository: *repo
    tag: *tag
    pullPolicy: Always
  ui-usvc:
    image: "erag-chatqna-conversation-ui"
    repository: *repo
    tag: *tag
    pullPolicy: Always
  vllm_gaudi:
    image: "erag-vllm-gaudi"
    repository: *repo
    tag: *tag
    pullPolicy: Always
    envs:
      LLM_VLLM_MODEL_NAME: *hpu_model
  vllm:
    image: "erag-vllm-cpu"
    repository: *repo
    tag: *tag
    pullPolicy: Always
    envs:
      LLM_VLLM_MODEL_NAME: *cpu_model
  langdtct-usvc:
    image: "erag-language-detection"
    repository: *repo
    tag: *tag
    pullPolicy: Always
    envfile: "src/comps/language_detection/impl/microservice/.env"
  fingerprint-usvc:
    image: "erag-system-fingerprint"
    repository: *repo
    tag: *tag
    pullPolicy: Always
