FROM vllm-cpu-base:latest

COPY compliance /compliance

WORKDIR /compliance/ospdt
COPY Dockerfile .

# CMD from base Dockerfile
WORKDIR /home/user
ENTRYPOINT ["python3", "-m", "vllm.entrypoints.openai.api_server"]
