FROM hierarchical-dataprep-usvc-base:latest

COPY compliance /compliance

WORKDIR /compliance/ospdt
COPY Dockerfile .
COPY uv.lock .

# CMD from base Dockerfile
WORKDIR /home/user/comps/hierarchical_dataprep
CMD ["python", "opea_hierarchical_dataprep_microservice.py"]
