# Copyright (C) 2024-2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

---
- name: Generate list of enabled namespaces
  ansible.builtin.include_role:
    name: utils
    tasks_from: get_namespaces.yaml
  tags:
    - install
    - uninstall

- name: Add labels for enabled namespaces
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ item }}"
        labels:
          erag-istio-protected: "true"
          istio.io/dataplane-mode: "ambient"
  loop: "{{ enabled_namespaces }}"
  when: istio_injection
  tags:
    - install

- name: Check if each namespace exists
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Namespace
    name: "{{ item }}"
  register: namespace_check_results
  loop: "{{ enabled_namespaces }}"
  tags:
    - install
    - uninstall

- name: Collect existing namespaces
  ansible.builtin.set_fact:
    existing_namespaces: >-
      {{ namespace_check_results.results
         | selectattr('resources', 'defined')
         | selectattr('resources', 'truthy')
         | map(attribute='item')
         | list }}
  tags:
    - install
    - uninstall

- name: Remove labels for enabled namespaces
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ item }}"
        labels:
          erag-istio-protected: null
          istio.io/dataplane-mode: null
  loop: "{{ existing_namespaces }}"
  when: not istio_injection
  tags:
    - install
    - uninstall
