FROM dpguard-base:latest

COPY compliance /compliance

WORKDIR /compliance/ospdt
COPY Dockerfile .
COPY uv.lock .

# CMD from base Dockerfile
WORKDIR /home/user/comps/guardrails/llm_guard_dataprep_guardrail/
CMD ["python", "opea_llm_guard_dataprep_guardrail_microservice.py"]
