FROM prompt_template-base:latest

COPY compliance /compliance

WORKDIR /compliance/ospdt
COPY Dockerfile .
COPY uv.lock .

# CMD from base Dockerfile
WORKDIR /home/user/comps/prompt_template
CMD ["python", "opea_prompt_template_microservice.py"]
