FROM ingestion-base:latest

COPY compliance /compliance

WORKDIR /compliance/ospdt
COPY Dockerfile .
COPY uv.lock .

# CMD from base Dockerfile
WORKDIR /home/user/comps/ingestion
CMD ["python", "opea_ingestion_microservice.py"]
