# Copyright (C) 2024-2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

---
- name: Check if the password file exists
  ansible.builtin.stat:
    path: "{{ password_file }}"
  register: password_file_stat
  tags:
    - install

- name: Create password file
  ansible.builtin.file:
    path: "{{ password_file }}"
    state: touch
    mode: '0600'
  when: not password_file_stat.stat.exists
  tags:
    - install

- name: Load the passwords from the file
  ansible.builtin.include_vars:
    file: "{{ password_file }}"
  when: password_file_stat.stat.exists
  tags:
    - install
