FROM text-extractor-base:latest

COPY compliance /compliance

WORKDIR /compliance/ospdt
COPY Dockerfile .
COPY uv.lock .

# CMD from base Dockerfile
WORKDIR /home/user/comps/text_extractor
CMD ["python", "opea_text_extractor_microservice.py"]
