FROM dataprep-base:latest

COPY compliance /compliance

WORKDIR /compliance/ospdt
COPY Dockerfile .
COPY uv.lock .

# CMD from base Dockerfile
WORKDIR /home/user/comps/dataprep
CMD ["python", "opea_dataprep_microservice.py"]
