FROM text-compression-base:latest

COPY compliance /compliance

WORKDIR /compliance/ospdt
COPY Dockerfile .
COPY uv.lock .

# CMD from base Dockerfile
WORKDIR /home/user/comps/text_compression
CMD ["python", "opea_text_compression_microservice.py"]
