# Copyright (C) 2024-2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

version: '3.8'

services:
  embedding-tei-model-server:
    image: ghcr.io/huggingface/text-embeddings-inference:cpu-1.6
    container_name: embedding-tei-model-server
    ports:
      - "${TEI_PORT}:80"
    volumes:
      - ./data:/data
    environment:
      NO_PROXY: ${NO_PROXY}
      HTTP_PROXY: ${HTTP_PROXY}
      HTTPS_PROXY: ${HTTPS_PROXY}
    command: ["--model-id", "${TEI_MODEL_NAME}"]
    runtime: runc
    ipc: host

  embedding_usvc:
    build:
      context: ../../../../../../
      dockerfile: ./comps/embeddings/impl/microservice/Dockerfile
    container_name: embedding-tei-microservice
    environment:
      NO_PROXY: ${NO_PROXY}
      HTTP_PROXY: ${HTTP_PROXY}
      HTTPS_PROXY: ${HTTPS_PROXY}
      EMBEDDING_CONNECTOR: ${EMBEDDING_CONNECTOR}
      EMBEDDING_MODEL_NAME: ${TEI_MODEL_NAME}
      EMBEDDING_MODEL_SERVER: tei
      EMBEDDING_MODEL_SERVER_ENDPOINT: http://localhost:${TEI_PORT}
    ipc: host
    runtime: runc
    network_mode: host
    restart: unless-stopped
    depends_on:
      - embedding-tei-model-server
