FROM system-fingerprint-base:latest

COPY compliance /compliance

WORKDIR /compliance/ospdt
COPY Dockerfile .
COPY uv.lock .

# CMD from base Dockerfile
WORKDIR /home/user/comps/system_fingerprint
ENTRYPOINT ["python", "opea_system_fingerprint_microservice.py"]
