FROM in-guard-base:latest

COPY compliance /compliance

WORKDIR /compliance/ospdt
COPY Dockerfile .
COPY uv.lock .

# CMD from base Dockerfile
WORKDIR /home/user/comps/guardrails/llm_guard_input_guardrail/
CMD ["python", "opea_llm_guard_input_guardrail_microservice.py"]
