# Copyright (C) 2024-2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

FROM ubuntu:22.04 AS dev

# install packages based on vllm/Dockerfile.cpu
RUN apt-get update -y \
    && apt-get install -y git gcc-12 g++-12 python3 python3-pip libtcmalloc-minimal4 libnuma-dev \
    && update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 10 --slave /usr/bin/g++ g++ /usr/bin/g++-12
RUN pip install --upgrade pip==24.3.1

RUN pip install intel-openmp==2025.0.1
ENV LD_PRELOAD="/usr/lib/x86_64-linux-gnu/libtcmalloc_minimal.so.4:/usr/local/lib/libiomp5.so"
RUN echo 'ulimit -c 0' >> ~/.bashrc
RUN pip install intel_extension_for_pytorch==2.5.0

WORKDIR /workspace
ENV PIP_EXTRA_INDEX_URL="https://download.pytorch.org/whl/cpu"

# install requirements based on vllm/requirements-build.txt
RUN pip install --upgrade cmake==3.31.1 ninja==1.11.1.2 packaging==24.2 setuptools==75.6.0 setuptools-scm==8.1.0 torch==2.5.1 wheel==0.45.0 jinja2==3.1.4 numpy==1.26.4

ENV VLLM_TARGET_DEVICE="cpu"
RUN pip install -v git+https://github.com/vllm-project/vllm@v0.7.2

ENTRYPOINT ["python3", "-m", "vllm.entrypoints.openai.api_server"]
