# Copyright (C) 2024-2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

FROM vault.habana.ai/gaudi-docker/1.20.0/ubuntu22.04/habanalabs/pytorch-installer-2.6.0:latest

ENV LANG=en_US.UTF-8

# create user and folders
RUN useradd -u 1000 -m -s /bin/bash user
USER user
ENV PATH="$PATH:/home/user/.local/bin"
WORKDIR /home/user/

ENV VLLM_TARGET_DEVICE="hpu"
RUN pip install --upgrade-strategy eager optimum[habana] --extra-index-url https://download.pytorch.org/whl/cpu
RUN pip install -v git+https://github.com/HabanaAI/vllm-fork.git@v0.6.6.post1+Gaudi-1.20.0 --extra-index-url https://download.pytorch.org/whl/cpu
RUN pip install triton==3.1.0 --ignore-installed

CMD ["/bin/bash"]
