FROM embedding-base:latest

COPY compliance /compliance

WORKDIR /compliance/ospdt
COPY Dockerfile .
COPY uv.lock .

# CMD from base Dockerfile
WORKDIR /home/user/comps/embeddings
CMD ["python", "opea_embedding_microservice.py"]
