FROM text-splitter-base:latest

COPY compliance /compliance

WORKDIR /compliance/ospdt
COPY Dockerfile .
COPY uv.lock .

# CMD from base Dockerfile
WORKDIR /home/user/comps/text_splitter
CMD ["python", "opea_text_splitter_microservice.py"]
