FROM torchserve_reranking-base:latest

COPY compliance /compliance

WORKDIR /compliance/ospdt
COPY Dockerfile .

# CMD from base Dockerfile
WORKDIR /home/user/
ENTRYPOINT ["/home/user/entrypoint.sh"]
