FROM ovms_embedding-base:latest

COPY compliance /compliance

WORKDIR /compliance/ospdt
COPY Dockerfile .
COPY uv.lock .

# CMD from base Dockerfile
WORKDIR /home/ovms/
ENTRYPOINT ["./entrypoint.sh"]
